### ISSUE TITLE
[Bug] Warden, team switch

### ISSUE THREAD

**Issue by destoer** [edgegamers/Jailbreak#39] opened 2024-02-10 12:26 UTC
Warden is not removed when they switch teams

**Comment by MSWS** [comment] 2024-02-10 21:09
It looks like the warden isn't being removed when they die either as of `1.1.0-alpha.1 (0b40f00)`.

**Comment by MSWS** [comment] 2024-02-10 21:42
Fix has been confirmed as working, will close this issue once merged into main.

**Closed** 2024-03-25 10:03 UTC
Labels: status::6 Complete, priority::3 Medium, type::1 Bug
